const problemsList = [
  {
    questionNumber: 1,
    title: "Two Sum",
    acceptance: 53.9,
    difficulty: "Easy",
    status: "solved",
    link: "two-sum",
  },
  {
    questionNumber: 2,
    title: "Add Two numbers",
    acceptance: 42.6,
    difficulty: "Medium",
    status: "solved",
    link: "add-two-number",
  },
  {
    questionNumber: 3,
    title: "Longest Substring Without Repeating Character",
    acceptance: 53.9,
    difficulty: "Medium",
    status: "attempted",
    link: "longest-substring-without-repeating-character",
  },
  {
    questionNumber: 4,
    title: "Median of Two Sorted Array",
    acceptance: 47.9,
    difficulty: "Hard",
    status: "",
    link: "median-of-two-sorted-array",
  },
  {
    questionNumber: 5,
    title: "Longest Palindromic Substring",
    acceptance: 47.2,
    difficulty: "Medium",
    status: "solved",
    link: "longest-palindromic-substring",
  },
  {
    questionNumber: 6,
    title: "Zig Zag Conversion",
    acceptance: 47.6,
    difficulty: "Medium",
    status: "",
    link: "zig-zag-conversion",
  },
  {
    questionNumber: 7,
    title: "Reverse Integer",
    acceptance: 28.5,
    difficulty: "Medium",
    status: "solved",
    link: "reverse-integer",
  },
  {
    questionNumber: 8,
    title: "String to Integer (atoi)",
    acceptance: 17.2,
    difficulty: "Medium",
    status: "solved",
    link: "string-to-integer-atoi",
  },
  {
    questionNumber: 9,
    title: "Palindrome Number",
    acceptance: 56.2,
    difficulty: "Easy",
    status: "solved",
    link: "palindrome-number",
  },
  {
    questionNumber: 10,
    title: "Regular Expression Matching",
    acceptance: 28.1,
    difficulty: "Hard",
    status: "",
    link: "regular-expression-matching",
  },
];
export default problemsList;
